export {
  ADMIN_CAPABILITY_PERMISSIONS,
  PERMISSION_CATEGORIES,
  PERMISSION_DEFINITIONS,
  PERMISSION_KEYS,
  SALES_DEFAULT_PERMISSIONS,
  SYSTEM_ROLE_NAMES,
  groupPermissionsByCategory,
  hasAdminCapability,
  hasEveryPermission,
  hasPermission,
  isPermissionKey,
  type PermissionCategory,
  type PermissionDefinition,
  type PermissionKey,
} from "./permissions";

export {
  createRoleSchema,
  createUserSchema,
  loginSchema,
  updateRoleSchema,
  updateUserActivationSchema,
  updateUserSchema,
  type CreateRoleInput,
  type CreateUserInput,
  type LoginInput,
  type UpdateRoleInput,
  type UpdateUserActivationInput,
  type UpdateUserInput,
} from "./schemas";

export type {
  ApiErrorBody,
  ApiFailure,
  ApiSuccess,
  AuthUser,
  PublicRole,
  RoleSummary,
} from "./types";

export {
  DEFAULT_API_PORT,
  DEFAULT_LOCAL_API_ORIGIN,
  DEFAULT_WEB_PORT,
} from "./runtime";

export {
  ACTIVITY_TYPE_LABELS,
  ACTIVITY_TYPES,
  COMPANY_SIZE_LABELS,
  COMPANY_SIZES,
  COMPANY_SOURCE_LABELS,
  COMPANY_SOURCES,
  DECISION_ROLE_LABELS,
  DECISION_ROLES,
  EVIDENCE_CATEGORIES,
  EVIDENCE_CATEGORY_LABELS,
  HYPOTHESIS_STATUS_LABELS,
  HYPOTHESIS_STATUSES,
  IMPORT_ENTITIES,
  IMPORT_ENTITY_LABELS,
  IMPORT_ROW_STATUSES,
  OPEN_OPPORTUNITY_STAGES,
  OPPORTUNITY_STAGE_LABELS,
  OPPORTUNITY_STAGES,
  PREFERRED_CHANNEL_LABELS,
  PREFERRED_CHANNELS,
  PRIORITIES,
  PRIORITY_LABELS,
  PRIORITY_THRESHOLDS,
  QUALIFICATION_MAX,
  QUALIFICATION_MIN,
  QUALIFICATION_TOTAL_MAX,
  QUALIFIED_PLUS_STAGES,
  STAGE_PROBABILITY_DEFAULTS,
  TASK_STATUS_LABELS,
  TASK_STATUSES,
  computeQualification,
  computeWeightedValue,
  defaultProbabilityForStage,
  formatQualificationLabel,
  isClosedStage,
  normalizeCompanyName,
  normalizeWebsiteDomain,
  scoreToPriority,
  QUALIFICATION_ACCESS_PENDING_HINT,
  PRELIMINARY_PRIORITY_THRESHOLDS,
  type ActivityType,
  type CompanySize,
  type CompanySource,
  type DecisionRole,
  type EvidenceCategory,
  type HypothesisStatus,
  type ImportEntity,
  type ImportRowStatus,
  type OpportunityStage,
  type PreferredChannel,
  type Priority,
  type TaskStatus,
} from "./crm";

export {
  COMPANY_SIZE_IMPORT_VALUES,
  COMPANY_SOURCE_IMPORT_VALUES,
  canonicalizeImportText,
  emptyToNull,
  foldImportHeader,
  foldImportToken,
  importGuide,
  matchImportColumn,
  parseCompanySize,
  parseCompanySource,
  parseControlledEnum,
  parseDecisionRole,
  parseOptionalEmail,
  parseOptionalScore,
  parseOptionalUrl,
  parsePreferredChannel,
} from "./import-format";

export {
  COMPANY_IMPORT_COLUMNS,
  CONTACT_IMPORT_COLUMNS,
  activityListQuerySchema,
  companyListQuerySchema,
  companyWriteSchema,
  contactListQuerySchema,
  contactWriteSchema,
  createActivitySchema,
  createCompanySchema,
  createContactSchema,
  createEvidenceSchema,
  createHypothesisSchema,
  createOpportunitySchema,
  createTaskSchema,
  evidenceWriteSchema,
  hypothesisWriteSchema,
  importCommitSchema,
  importParseQuerySchema,
  moneyInputSchema,
  opportunityListQuerySchema,
  opportunityWriteSchema,
  paginationQuerySchema,
  probabilitySchema,
  researchListQuerySchema,
  taskListQuerySchema,
  updateActivitySchema,
  updateCompanySchema,
  updateContactSchema,
  updateEvidenceSchema,
  updateHypothesisSchema,
  updateOpportunitySchema,
  updateTaskSchema,
  type ActivityListQuery,
  type CompanyListQuery,
  type ContactListQuery,
  type CreateActivityInput,
  type CreateCompanyInput,
  type CreateContactInput,
  type CreateEvidenceInput,
  type CreateHypothesisInput,
  type CreateOpportunityInput,
  type CreateTaskInput,
  type ImportCommitInput,
  type OpportunityListQuery,
  type ResearchListQuery,
  type TaskListQuery,
  type UpdateActivityInput,
  type UpdateCompanyInput,
  type UpdateContactInput,
  type UpdateEvidenceInput,
  type UpdateHypothesisInput,
  type UpdateOpportunityInput,
  type UpdateTaskInput,
} from "./crm-schemas";

export type {
  ActivityRecord,
  CompanyDetail,
  CompanySummary,
  ContactDetail,
  ContactSummary,
  DashboardData,
  DashboardMetrics,
  HypothesisRecord,
  ImportPreview,
  ImportPreviewRow,
  ImportResult,
  OpportunityDetail,
  OpportunitySummary,
  PaginatedResult,
  PipelineStageMetric,
  ResearchEvidenceRecord,
  TaskRecord,
  UserRef,
} from "./crm-types";

export {
  RECRUITMENT_IN_PROCESS_STAGES,
  RECRUITMENT_ROLE_TYPES,
  RECRUITMENT_ROLE_TYPE_LABELS,
  RECRUITMENT_STAGE_LABELS,
  RECRUITMENT_STAGES,
  type RecruitmentRoleType,
  type RecruitmentStage,
} from "./recruitment";

export {
  createRecruitmentCandidateSchema,
  recruitmentListQuerySchema,
  recruitmentWriteSchema,
  updateRecruitmentCandidateSchema,
  type CreateRecruitmentCandidateInput,
  type RecruitmentCandidateDetail,
  type RecruitmentCandidateSummary,
  type RecruitmentListQuery,
  type RecruitmentMetrics,
  type UpdateRecruitmentCandidateInput,
} from "./recruitment-schemas";
